name: Gmail to Google Sheet Updater

on:
  # This allows it to run on a schedule (every hour)
  schedule:
    - cron: '0 * * * *'  # runs every hour at minute 0
  # This allows manual triggering from GitHub's UI
  workflow_dispatch:

jobs:
  run-agent:
    runs-on: ubuntu-latest

    env:
      GMAIL_TOKEN_JSON: ${{ secrets.GMAIL_TOKEN_JSON }}
      SHEETS_TOKEN_JSON: ${{ secrets.SHEETS_TOKEN_JSON }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🚀 Run ReAct Agent script
        run: |
          python src/react_agent/graph.py
